version: '3.7'

services:
  mdev-db:
    image: mysql:5.7
    container_name: mdev-db-dev
    command: --sql_mode=""
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./docker/db:/var/lib/mysql
    ports:
      - '5002:3306'

  mdev-php:
    container_name: mdev-php-dev
    build: docker/php-fpm
    environment:
      APP_ENV: dev
      APP_VERSION: dev
      DATABASE_URL: mysql://root:@mdev-db:3306/mdev_dev
    working_dir: /app
    volumes:
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
      - .:/app:cached
    depends_on:
      - mdev-db

  mdev-nginx:
    image: nginx:latest
    container_name: mdev-nginx-dev
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/app:cached
    ports:
      - '5003:80'
    depends_on:
      - mdev-php